SONG = {
    "rowLen": 7350,
    "endPattern": 11,
    "songData": [
        {
            "osc1_oct": 4,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 0,
            "osc1_vol": 192,
            "osc1_waveform": 3,
            "osc2_oct": 4,
            "osc2_det": 0,
            "osc2_detune": 7,
            "osc2_xenv": 0,
            "osc2_vol": 201,
            "osc2_waveform": 3,
            "noise_fader": 0,
            "env_attack": 789,
            "env_sustain": 1234,
            "env_release": 13636,
            "env_master": 191,
            "fx_filter": 2,
            "fx_freq": 5839,
            "fx_resonance": 254,
            "fx_delay_time": 6,
            "fx_delay_amt": 121,
            "fx_pan_freq": 6,
            "fx_pan_amt": 147,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 1,
            "lfo_freq": 6,
            "lfo_amt": 195,
            "lfo_waveform": 0,
            "p": [
                2,
                3,
                2,
                2,
                2,
                3,
                2,
                3,
                4,
                5
            ],
            "c": [
                {
                    "n": [
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        161,
                        0,
                        0,
                        0,
                        161,
                        0,
                        0,
                        0,
                        164,
                        0,
                        0,
                        0,
                        163,
                        0,
                        0,
                        0,
                        161,
                        0,
                        0,
                        0,
                        168,
                        0,
                        0,
                        0,
                        166,
                        0,
                        0,
                        0,
                        164,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        168,
                        0,
                        0,
                        0,
                        166,
                        0,
                        0,
                        0,
                        164,
                        0,
                        0,
                        0,
                        163,
                        0,
                        0,
                        0,
                        161,
                        0,
                        0,
                        0,
                        161,
                        0,
                        0,
                        0,
                        163,
                        0,
                        0,
                        0,
                        164,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        164,
                        0,
                        0,
                        0,
                        163,
                        0,
                        0,
                        0,
                        161,
                        0,
                        0,
                        0,
                        161,
                        0,
                        0,
                        0,
                        166,
                        0,
                        0,
                        0,
                        164,
                        0,
                        0,
                        0,
                        163,
                        0,
                        0,
                        0,
                        163,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        168,
                        0,
                        0,
                        0,
                        166,
                        0,
                        0,
                        0,
                        164,
                        0,
                        0,
                        0,
                        164,
                        0,
                        0,
                        0,
                        163,
                        0,
                        0,
                        0,
                        163,
                        0,
                        0,
                        0,
                        168,
                        0,
                        0,
                        0,
                        166,
                        0,
                        0,
                        0
                    ]
                }
            ]
        },
        {
            "osc1_oct": 7,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 1,
            "osc1_vol": 128,
            "osc1_waveform": 0,
            "osc2_oct": 7,
            "osc2_det": 0,
            "osc2_detune": 0,
            "osc2_xenv": 1,
            "osc2_vol": 128,
            "osc2_waveform": 0,
            "noise_fader": 255,
            "env_attack": 100,
            "env_sustain": 0,
            "env_release": 3636,
            "env_master": 59,
            "fx_filter": 2,
            "fx_freq": 500,
            "fx_resonance": 254,
            "fx_delay_time": 0,
            "fx_delay_amt": 27,
            "fx_pan_freq": 0,
            "fx_pan_amt": 0,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 0,
            "lfo_freq": 0,
            "lfo_amt": 0,
            "lfo_waveform": 0,
            "p": [
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2,
                2
            ],
            "c": [
                {
                    "n": [
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        137,
                        0,
                        0,
                        0,
                        137,
                        0,
                        0,
                        0,
                        135,
                        0,
                        0,
                        0,
                        135,
                        0,
                        0,
                        0,
                        134,
                        0,
                        0,
                        0,
                        132,
                        0,
                        0,
                        0,
                        132,
                        0,
                        0,
                        0,
                        132,
                        0,
                        0,
                        0
                    ]
                }
            ]
        },
        {
            "osc1_oct": 8,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 0,
            "osc1_vol": 0,
            "osc1_waveform": 0,
            "osc2_oct": 8,
            "osc2_det": 0,
            "osc2_detune": 0,
            "osc2_xenv": 0,
            "osc2_vol": 0,
            "osc2_waveform": 0,
            "noise_fader": 60,
            "env_attack": 50,
            "env_sustain": 419,
            "env_release": 4607,
            "env_master": 130,
            "fx_filter": 1,
            "fx_freq": 10332,
            "fx_resonance": 120,
            "fx_delay_time": 4,
            "fx_delay_amt": 16,
            "fx_pan_freq": 5,
            "fx_pan_amt": 108,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 0,
            "lfo_freq": 5,
            "lfo_amt": 187,
            "lfo_waveform": 0,
            "p": [
                0,
                0,
                2,
                2,
                0,
                0,
                2,
                2,
                2,
                2
            ],
            "c": [
                {
                    "n": [
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        111,
                        0,
                        0,
                        0,
                        120,
                        0,
                        0,
                        0,
                        111,
                        0,
                        0,
                        0,
                        120,
                        0,
                        0,
                        0,
                        111,
                        0,
                        0,
                        0,
                        120,
                        0,
                        0,
                        0,
                        111,
                        0,
                        0,
                        0,
                        120,
                        0,
                        0,
                        0
                    ]
                }
            ]
        }
    ],
    "songLen": 50
}

playSong = () => new MusicGenerator(SONG).createAudioBuffer(buffer => {
    const source = audioCtx.createBufferSource();
    source.buffer = buffer;
    source.loop = true;

    const gainNode = audioCtx.createGain();
    gainNode.gain.value = SONG_VOLUME;
    gainNode.connect(audioCtx.destination);
    source.connect(gainNode);
    source.nomangle(start)();

    playSong = () => 0;
    setSongVolume = (x) => {
        SONG_VOLUME = x;
        gainNode.gain.value = x;
    }
});

SONG_VOLUME = 0.5;
setSongVolume = (x) => SONG_VOLUME = x;
